name: fluid_app
description: Fluid app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 4.0.4
  sensors: 0.4.1+7

dev_dependencies:
  pedantic: 1.9.0

flutter:
  uses-material-design: true
